FROM ubuntu:22.04 as base

WORKDIR /gh-runner-automation

COPY ./modules/aci/script ./script

RUN \
    apt-get update -y && \
    apt-get install build-essential -y && \
    apt-get install curl -y && \
    apt-get install dotnet-sdk-6.0 -y && \
    apt-get install tar && \
    DEBIAN_FRONTEND=noninteractive apt-get install git -y
# RUN git clone https://github.com/armkiyas/gh-runner-automation.git
RUN chmod +x /script/configureLinuxRunner.sh
ENTRYPOINT /script/configureLinuxRunner.sh
